name: Random workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Guild
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_TOKEN }}

    - name: Testing
      run: |
        cd test
        bash random.sh
